/**
 * The country graph, and the search primitives everything else is built from.
 *
 * Generated by `scripts/build-data.ts` and committed, so it loads synchronously
 * with the bundle — validation, autocomplete and reveals never wait on a
 * network round-trip.
 */
import data from '../data/graph.json' with { type: 'json' }

export type CountryCode = string

export type Country = {
  /** Common English name, as shown once a country is named. */
  name: string
  flag: string
  /** ISO 3166-1 numeric — joins this country to its globe polygon. */
  ccn3: string
  latlng: [number, number]
  /** Official name and alternate spellings, for autocomplete. */
  alt: string[]
  /** Land neighbours. Always symmetric: if A borders B, B borders A. */
  borders: CountryCode[]
  /**
   * Sea crossings: fixed links, ferries and narrow straits, curated in
   * `data/sea-links.json`. Kept apart from `borders` so that "shares a land
   * border" stays a question with an answer, and so the globe can draw a
   * crossing as the different kind of thing it is.
   */
  sea: CountryCode[]
  /** Connected group, over land and sea together. */
  component: number
}

// What things cost lives in `./terrain`, an import-free leaf, because the build
// script and the pool's own tests need the same numbers and cannot import this
// module — it reads `src/data/graph.json`, which the build script writes.
// Re-exported so the rest of the game goes on asking the graph.
// The extension is not decoration and not a style slip: `scripts/build-og.ts`
// imports this module, which pulls it into the Node project, where module
// resolution is `nodenext` and a relative import without one is an error.
import { ROUGH_COST, SEA_COST } from './terrain.ts'
export { ROUGH_COST, SEA_COST }

export const GRAPH = data as unknown as Record<CountryCode, Country>

export const CODES = Object.keys(GRAPH)

export function country(code: CountryCode): Country {
  const found = GRAPH[code]
  if (!found) throw new Error(`unknown country code: ${code}`)
  return found
}

export function exists(code: CountryCode): boolean {
  return code in GRAPH
}

/** Land neighbours only. */
export function neighbours(code: CountryCode): CountryCode[] {
  return country(code).borders
}

/** Everywhere you can get to in one move, by land or by sea. */
export function links(code: CountryCode): CountryCode[] {
  const found = country(code)
  return found.sea.length === 0 ? found.borders : [...found.borders, ...found.sea]
}

/** Whether these two are joined by water rather than by a land border. */
export function isSea(a: CountryCode, b: CountryCode): boolean {
  return country(a).sea.includes(b)
}

export function borders(a: CountryCode, b: CountryCode): boolean {
  return country(a).borders.includes(b)
}

/**
 * Every country but these — the `within` set for a graph with countries shut.
 *
 * Closures are expressed by subtraction rather than by a parameter on every
 * search, because `within` already means exactly this. Two ways to say it would
 * be two things to keep in agreement.
 */
export function without(excluded: Iterable<CountryCode>): Set<CountryCode> {
  const remaining = new Set(CODES)
  for (const code of excluded) remaining.delete(code)
  return remaining
}

/**
 * Countries reachable from `to` without using the `from`–`to` link: the far
 * side of that link.
 *
 * Every sea crossing is a bridge, because the curated list forms a forest over
 * the landmasses. Cutting a bridge splits the world in two, and a simple route
 * between two countries uses it exactly when they sit on opposite sides —
 * crossing it and coming back would mean using the same link twice. That is
 * what makes "could this crossing matter to this puzzle" an exact question
 * rather than a guess.
 */
export function beyond(from: CountryCode, to: CountryCode): Set<CountryCode> {
  const seen = new Set([to])
  const queue = [to]
  for (let head = 0; head < queue.length; head++) {
    const current = queue[head]
    for (const link of links(current)) {
      if (seen.has(link)) continue
      if (current === to && link === from) continue
      if (current === from && link === to) continue
      seen.add(link)
      queue.push(link)
    }
  }
  return seen
}

/** Whether a land route between these two exists at all. */
export function connectable(a: CountryCode, b: CountryCode): boolean {
  return country(a).component === country(b).component
}

/**
 * What arriving in `to` from `from` costs: a land border 1, a sea crossing
 * more, and more again for ground the round has put in the rough.
 *
 * The rough is charged against the destination and not the link, so every way
 * into a rough country costs the same premium — which is the whole difference
 * between it and a crossing.
 */
export function cost(from: CountryCode, to: CountryCode, rough?: ReadonlySet<CountryCode>): number {
  const base = isSea(from, to) ? SEA_COST : 1
  return rough?.has(to) ? base + (ROUGH_COST - 1) : base
}

/**
 * The cheapest route between two countries: what it costs and how it goes.
 *
 * Dijkstra rather than breadth-first, so that links are free to cost different
 * amounts. Over 165 countries a linear scan of the frontier is a few thousand
 * comparisons, which is far cheaper to read than a heap and fast enough that
 * nothing here has ever been worth measuring.
 *
 * Two tie-breaks keep a route stable, and both matter: the frontier prefers the
 * country it discovered first, and neighbours are walked in code order. Between
 * them they reproduce exactly the route breadth-first search used to return, so
 * `detours` and the share grid do not quietly change shape.
 *
 * The two ways a round bends this are deliberately different shapes. `within`
 * *subtracts* — a closed country is one the graph no longer contains, which is
 * why closures need no parameter of their own. `rough` *prices* — the country
 * is still there and still playable, it just costs more to be in. Additive
 * cost cannot be said by subtraction, which is the whole reason this second
 * parameter exists rather than being folded into the first.
 */
export function search(
  from: CountryCode,
  to: CountryCode,
  within?: ReadonlySet<CountryCode>,
  rough?: ReadonlySet<CountryCode>,
): { cost: number; path: CountryCode[] } | null {
  if (within && (!within.has(from) || !within.has(to))) return null
  if (from === to) return { cost: 0, path: [from] }

  const best = new Map<CountryCode, number>([[from, 0]])
  const cameFrom = new Map<CountryCode, CountryCode | null>([[from, null]])
  const settled = new Set<CountryCode>()
  const discovered: CountryCode[] = [from]

  for (;;) {
    let current: CountryCode | null = null
    let cheapest = Number.POSITIVE_INFINITY
    // Strictly cheaper, so that among equal costs the earliest discovery holds.
    for (const code of discovered) {
      if (settled.has(code)) continue
      const so_far = best.get(code)!
      if (so_far < cheapest) {
        current = code
        cheapest = so_far
      }
    }
    if (current === null) return null

    if (current === to) {
      const path: CountryCode[] = []
      for (let step: CountryCode | null = to; step; step = cameFrom.get(step) ?? null) {
        path.push(step)
      }
      return { cost: cheapest, path: path.reverse() }
    }

    settled.add(current)
    for (const neighbour of [...links(current)].sort()) {
      if (settled.has(neighbour)) continue
      if (within && !within.has(neighbour)) continue
      const next = cheapest + cost(current, neighbour, rough)
      const known = best.get(neighbour)
      if (known === undefined) {
        best.set(neighbour, next)
        cameFrom.set(neighbour, current)
        discovered.push(neighbour)
      } else if (next < known) {
        best.set(neighbour, next)
        cameFrom.set(neighbour, current)
      }
    }
  }
}

/**
 * What the cheapest route from here to everywhere costs.
 *
 * One search rather than one per destination: `search` stops as soon as it
 * settles the country it was asked about, so asking it 165 times over does 165
 * times the work for an answer the first run already had most of.
 */
export function costsFrom(
  source: CountryCode,
  within?: ReadonlySet<CountryCode>,
  rough?: ReadonlySet<CountryCode>,
): Map<CountryCode, number> {
  if (within && !within.has(source)) return new Map()

  const best = new Map<CountryCode, number>([[source, 0]])
  const settled = new Set<CountryCode>()
  const discovered: CountryCode[] = [source]

  for (;;) {
    let current: CountryCode | null = null
    let cheapest = Number.POSITIVE_INFINITY
    for (const code of discovered) {
      if (settled.has(code)) continue
      const so_far = best.get(code)!
      if (so_far < cheapest) {
        current = code
        cheapest = so_far
      }
    }
    if (current === null) return best

    settled.add(current)
    for (const neighbour of links(current)) {
      if (settled.has(neighbour)) continue
      if (within && !within.has(neighbour)) continue
      const next = cheapest + cost(current, neighbour, rough)
      const known = best.get(neighbour)
      if (known === undefined) {
        best.set(neighbour, next)
        discovered.push(neighbour)
      } else if (next < known) {
        best.set(neighbour, next)
      }
    }
  }
}

/**
 * What the cheapest route costs, or `null` if the two are on different
 * landmasses. `within` restricts the search to a subset of the graph, which is
 * how a player's own placements are checked for a win.
 */
export function distance(
  from: CountryCode,
  to: CountryCode,
  within?: ReadonlySet<CountryCode>,
  rough?: ReadonlySet<CountryCode>,
): number | null {
  return search(from, to, within, rough)?.cost ?? null
}

/**
 * One cheapest route between two countries, inclusive of both ends, or `null`
 * if there is none.
 */
export function shortestPath(
  from: CountryCode,
  to: CountryCode,
  within?: ReadonlySet<CountryCode>,
  rough?: ReadonlySet<CountryCode>,
): CountryCode[] | null {
  return search(from, to, within, rough)?.path ?? null
}

/** Further than any route can cost, for a frontier that has not been reached. */
const FAR = 0x3fffffff

/**
 * The cheapest route from `from` to `to` that runs *through* `via`, or `null`
 * where the map allows no such route.
 *
 * This replaced a Steiner tree, and the difference is the whole of the dogleg. A
 * tree only had to *reach* the waypoint, so the cheapest board hung it off the
 * side as a dead end and the route went past it. A route has to go in one border
 * and out another, which is what a dogleg is.
 *
 * That inverts the arithmetic, and the inversion is worth stating plainly
 * because the comment here used to say the opposite: `d(from, via) + d(via, to)`
 * was an *over*-estimate of the floor on 84% of waypoints. It is now a **lower
 * bound** — met on 86% of them, and exceeded on the other 14%, wherever the
 * cheapest way in blocks the cheapest way out.
 *
 * `null` is not a failure. It is the third rule of the mechanic falling out of
 * the second rather than being written down separately: a country with only one
 * way in and out cannot be routed through, so it cannot be a waypoint. Portugal,
 * Iceland and Lesotho have a single link each and can never be one; anything
 * behind a cut vertex relative to both ends is refused for the same reason.
 *
 * ## How
 *
 * Two internally-disjoint paths out of the waypoint, one to each end, at the
 * lowest total cost — a minimum-cost flow of value two, from `via` to a sink fed
 * by both endpoints, over the graph with every country split in half:
 *
 *     enter(v) --[capacity 1, cost: v's rough premium]--> leave(v)
 *     leave(u) --[capacity 1, cost: the link]--> enter(v)     for every link u–v
 *
 * The split arc is what makes the two paths disjoint — a country carries one
 * unit or none — and disabling it for `from`, `to` and `via` is what stops a
 * path running *through* somewhere the route is supposed to start, end or turn.
 *
 * The premium bookkeeping falls out, where the tree needed a correction for it:
 * each country between the ends is charged once, by its own split arc, and no
 * terminal is charged at all. That is exactly what the player pays, because
 * `newGame` refuses a rough endpoint and a rough waypoint — and it is a better
 * reason for that second refusal than the one it used to have. The flow *leaves*
 * the waypoint rather than arriving at it, so a premium there would go
 * uncharged.
 *
 * Augmented by two queue-based Bellman–Ford passes rather than by Suurballe's
 * potentials, for the same reason `search` scans its frontier rather than
 * keeping a heap: the graph is small, the potential transform and the path
 * reversal are the two things that go subtly wrong, and being far too simple to
 * be wrong is what this module is priced around. Suurballe earns its place as
 * the *independent* second opinion, in `scripts/build-data.ts`'s verification
 * pass and in the tests — a different algorithm for one definition, standing
 * where `cheapest` does.
 */
export function searchVia(
  from: CountryCode,
  to: CountryCode,
  via: CountryCode,
  within?: ReadonlySet<CountryCode>,
  rough?: ReadonlySet<CountryCode>,
): { cost: number; path: CountryCode[] } | null {
  if (from === to || via === from || via === to) return null
  for (const terminal of [from, to, via]) {
    if (!exists(terminal)) return null
    if (within && !within.has(terminal)) return null
  }

  const codes = within ? CODES.filter((code) => within.has(code)) : CODES
  const node = new Map(codes.map((code, at) => [code, at]))
  const enter = (at: number) => at * 2
  const leave = (at: number) => at * 2 + 1
  const sink = codes.length * 2

  const head = new Int32Array(sink + 1).fill(-1)
  const onward: number[] = []
  const target: number[] = []
  const spare: number[] = []
  const price: number[] = []
  /** An arc and its residual, so that `arc ^ 1` is always the way back. */
  const arc = (tail: number, tip: number, capacity: number, weight: number) => {
    target.push(tip)
    spare.push(capacity)
    price.push(weight)
    onward.push(head[tail])
    head[tail] = target.length - 1
    target.push(tail)
    spare.push(0)
    price.push(-weight)
    onward.push(head[tip])
    head[tip] = target.length - 1
  }

  const terminals = new Set([from, to, via])
  codes.forEach((code, at) => {
    const premium = rough?.has(code) ? ROUGH_COST - 1 : 0
    arc(enter(at), leave(at), terminals.has(code) ? 0 : 1, premium)
    // Sorted for the same reason `search` sorts: the route this returns is read
    // by `detours` and drawn on the share card, so it may not quietly change
    // shape when the underlying data is regenerated.
    for (const link of [...links(code)].sort()) {
      const next = node.get(link)
      if (next === undefined) continue
      arc(leave(at), enter(next), 1, isSea(code, link) ? SEA_COST : 1)
    }
  })
  arc(enter(node.get(from)!), sink, 1, 0)
  arc(enter(node.get(to)!), sink, 1, 0)

  const source = leave(node.get(via)!)
  let cost = 0
  for (let unit = 0; unit < 2; unit++) {
    // Bellman–Ford rather than Dijkstra: a residual arc carries the negative of
    // the weight it undoes, and Dijkstra cannot be told that.
    const best = new Int32Array(sink + 1).fill(FAR)
    const cameBy = new Int32Array(sink + 1).fill(-1)
    const queued = new Uint8Array(sink + 1)
    best[source] = 0
    queued[source] = 1
    const pending = [source]
    for (let head_ = 0; head_ < pending.length; head_++) {
      const current = pending[head_]
      queued[current] = 0
      for (let step = head[current]; step >= 0; step = onward[step]) {
        if (spare[step] <= 0) continue
        const reach = best[current] + price[step]
        // Strictly better, so that among equal costs the first way found holds.
        if (reach >= best[target[step]]) continue
        best[target[step]] = reach
        cameBy[target[step]] = step
        if (queued[target[step]]) continue
        queued[target[step]] = 1
        pending.push(target[step])
      }
    }
    // One unit can always be pushed if the waypoint is reachable at all; it is
    // the *second* that asks whether there is another way round, and a waypoint
    // that fails here is one the round could only ever have doubled back out of.
    if (best[sink] >= FAR) return null
    cost += best[sink]
    for (let at = sink; at !== source; at = target[cameBy[at] ^ 1]) {
      spare[cameBy[at]] -= 1
      spare[cameBy[at] ^ 1] += 1
    }
  }

  // The flow is acyclic — every link costs at least one, so no cycle is free to
  // carry anything — which is what lets it be read back as exactly two walks.
  const walked = new Uint8Array(target.length)
  const legs: CountryCode[][] = []
  for (let leg = 0; leg < 2; leg++) {
    const trail: CountryCode[] = [via]
    let at = source
    for (;;) {
      let step = -1
      for (let out = head[at]; out >= 0; out = onward[out]) {
        // Forward arcs only, saturated, and not already claimed by the other leg.
        if ((out & 1) === 1 || walked[out] || spare[out] !== 0) continue
        step = out
        break
      }
      if (step < 0) return null
      walked[step] = 1
      at = target[step]
      if (at === sink) break
      if ((at & 1) === 1) continue
      const arrived = codes[at >> 1]
      trail.push(arrived)
      if (arrived === from || arrived === to) break
    }
    legs.push(trail)
  }

  const [first, second] = legs
  const inward = first[first.length - 1] === from ? first : second
  const outward = inward === first ? second : first
  if (inward[inward.length - 1] !== from || outward[outward.length - 1] !== to) return null
  return { cost, path: [...inward].reverse().concat(outward.slice(1)) }
}

/** What the cheapest route through `via` costs, or `null` if there is none. */
export function costVia(
  from: CountryCode,
  to: CountryCode,
  via: CountryCode,
  within?: ReadonlySet<CountryCode>,
  rough?: ReadonlySet<CountryCode>,
): number | null {
  return searchVia(from, to, via, within, rough)?.cost ?? null
}

/** One cheapest route through `via`, inclusive of all three, or `null`. */
export function routeVia(
  from: CountryCode,
  to: CountryCode,
  via: CountryCode,
  within?: ReadonlySet<CountryCode>,
  rough?: ReadonlySet<CountryCode>,
): CountryCode[] | null {
  return searchVia(from, to, via, within, rough)?.path ?? null
}
