/**
 * The country order that free-play links are written in.
 *
 * A shared round is encoded as one byte per country — an index into this list —
 * so **this order is the wire format**. Move an entry and every link ever
 * shared starts decoding to a different country: not a broken link, a link to
 * the wrong puzzle, which is the one failure here nobody would notice.
 *
 * So the list is append-only, and deliberately kept apart from
 * `src/data/graph.json`. That file is generated: `scripts/build-data.ts` sorts
 * by alpha-3 and drops any country without a polygon at 110m, so its key order
 * is a function of the upstream data and shifts the moment the data does. This
 * list is hand-held source that only ever grows:
 *
 *   - a new country is appended at the end, never inserted in sorted position
 *   - a country dropped from the graph keeps its slot here forever, as a
 *     tombstone, so the indices after it do not move
 *
 * `scripts/build-data.ts` checks both, and fails the build with instructions
 * rather than letting a rebuild quietly renumber the world.
 *
 * One byte is 256 slots. 165 are spoken for.
 */
export const LINK_CODES: string[] = [
  'AFG',
  'AGO',
  'ALB',
  'ARE',
  'ARG',
  'ARM',
  'AUS',
  'AUT',
  'AZE',
  'BDI',
  'BEL',
  'BEN',
  'BFA',
  'BGD',
  'BGR',
  'BHS',
  'BIH',
  'BLR',
  'BLZ',
  'BOL',
  'BRA',
  'BRN',
  'BTN',
  'BWA',
  'CAF',
  'CAN',
  'CHE',
  'CHL',
  'CHN',
  'CIV',
  'CMR',
  'COD',
  'COG',
  'COL',
  'CRI',
  'CUB',
  'CYP',
  'CZE',
  'DEU',
  'DJI',
  'DNK',
  'DOM',
  'DZA',
  'ECU',
  'EGY',
  'ERI',
  'ESP',
  'EST',
  'ETH',
  'FIN',
  'FJI',
  'FRA',
  'GAB',
  'GBR',
  'GEO',
  'GHA',
  'GIN',
  'GMB',
  'GNB',
  'GNQ',
  'GRC',
  'GTM',
  'GUY',
  'HND',
  'HRV',
  'HTI',
  'HUN',
  'IDN',
  'IND',
  'IRL',
  'IRN',
  'IRQ',
  'ISL',
  'ISR',
  'ITA',
  'JAM',
  'JOR',
  'JPN',
  'KAZ',
  'KEN',
  'KGZ',
  'KHM',
  'KOR',
  'KWT',
  'LAO',
  'LBN',
  'LBR',
  'LBY',
  'LKA',
  'LSO',
  'LTU',
  'LUX',
  'LVA',
  'MAR',
  'MDA',
  'MDG',
  'MEX',
  'MKD',
  'MLI',
  'MMR',
  'MNE',
  'MNG',
  'MOZ',
  'MRT',
  'MWI',
  'MYS',
  'NAM',
  'NER',
  'NGA',
  'NIC',
  'NLD',
  'NOR',
  'NPL',
  'NZL',
  'OMN',
  'PAK',
  'PAN',
  'PER',
  'PHL',
  'PNG',
  'POL',
  'PRK',
  'PRT',
  'PRY',
  'QAT',
  'ROU',
  'RUS',
  'RWA',
  'SAU',
  'SDN',
  'SEN',
  'SLB',
  'SLE',
  'SLV',
  'SOM',
  'SRB',
  'SSD',
  'SUR',
  'SVK',
  'SVN',
  'SWE',
  'SWZ',
  'SYR',
  'TCD',
  'TGO',
  'THA',
  'TJK',
  'TKM',
  'TLS',
  'TTO',
  'TUN',
  'TUR',
  'TZA',
  'UGA',
  'UKR',
  'URY',
  'USA',
  'UZB',
  'VEN',
  'VNM',
  'VUT',
  'YEM',
  'ZAF',
  'ZMB',
  'ZWE',
]

/** How many slots a one-byte index can address. */
export const LINK_CODE_LIMIT = 256
